---
apiVersion: v1
kind: ConfigMap
metadata:
  name: heartbeat-deployment-config
  namespace: kube-system
  labels:
    k8s-app: heartbeat
data:
  heartbeat.yml: |-
    heartbeat.monitors:
    - type: http
      schedule: ‘@every 5s’
      urls:
        - "apms-service.ai.svc:80"
      fields:
          env: dev
          tags: dev-env
          site: ASIa
          name: apms-service
      check.response.status: 404
      fields_under_root: true
    heartbeat.autodiscover:
      providers:
        - type: kubernetes
          templates:
            - condition:
                contains.equals:
                  kubernetes.labels.heartbeat_type: http
              config:
                - type: http
                  urls: ["http://${data.host}:${data.kubernetes.labels.heartbeat_port}/${data.kubernetes.labels.heartbeat_url}"]
                  id: "${data.kubernetes.pod.name}"
                  check.response.status: 200
                  schedule: "@every 1s"
                  timeout: 2s
            - condition.equals:
                kubernetes.labels.heartbeat_type: tcp
              config:
                - type: tcp
                  hosts: ["${data.host}:${data.kubernetes.labels.heartbeat_port}"]
                  schedule: "@every 1s"
                  timeout: 2s
        - type: kubernetes
          templates:
            - condition:
                contains:
                  kubernetes.labels.app: apms
              config:
                - type: icmp
                  hosts: ["${data.host}:${data.port}"]
                  schedule: "@every 1s"
                  timeout: 5s
        - type: kubernetes
          templates:
            - config:
                - type: icmp
                  hosts: ["${data.host}"]
                  schedule: ‘*/5 * * * * * *’
        - type: kubernetes
          templates:
            - config:
                - type: tcp
                  hosts: ["${data.host}:${data.port}"]
                  schedule: "@every 1s"
                  timeout: 5s
    name: heartbeat-monitoring
    output:
      elasticsearch:
        hosts: ${ELASTICSEARCH_HOSTS}
        username: ${ELASTICSEARCH_USERNAME}
        password: ${ELASTICSEARCH_PASSWORD}
        ssl.verification_mode: "none"
    setup:
      kibana:
        ssl.verification_mode: "none"
    processors:
      - add_cloud_metadata:
      - add_docker_metadata:
      - add_host_metadata:
      - add_id: ~
      - add_kubernetes_metadata:
          include_annotations:
            - annotation_to_include
    add_resource_metadata:
        namespace:
          enabled: true
        node:
          enabled: true
    xpack.monitoring.enabled: true  
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: heartbeat
  namespace: kube-system
  labels:
    k8s-app: heartbeat
spec:
  template:
    metadata:
      labels:
        k8s-app: heartbeat
    spec:
      serviceAccountName: heartbeat
      hostNetwork: false
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: heartbeat
        image: docker.elastic.co/beats/heartbeat:7.6.0
        args: [
          "-c", "/etc/heartbeat.yml",
          "-e",
        ]
        env:
        - name: ELASTIC_CLOUD_ID
        - name: ELASTIC_CLOUD_AUTH
        - name: ELASTICSEARCH_HOSTS
          value: "https://ai-dev-prod-es-http.elasticsearch.svc"
        - name: KIBANA_HOST
          value: "https://ai-dev-kibana-kb-http.elasticsearch.svc"
        - name: ELASTICSEARCH_USERNAME
          value: "elastic"
        - name: ELASTICSEARCH_PASSWORD
          value: "**********"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/heartbeat.yml
          readOnly: true
          subPath: heartbeat.yml
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: heartbeat-deployment-config
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: heartbeat
subjects:
- kind: ServiceAccount
  name: heartbeat
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: heartbeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: heartbeat
  labels:
    k8s-app: heartbeat
rules:
- apiGroups: [""]
  resources:
  - nodes
  - namespaces
  - events
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  - deployments
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - nodes/stats
  verbs:
  - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: heartbeat
  namespace: kube-system
  labels:
    k8s-app: heartbeat