apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: ai-dev-kibana
spec:
  version: 7.6.0
  count: 1
  elasticsearchRef:
    name: "ai-dev-prod"
  #http:
  #  service:
  #    spec:
  #      type: LoadBalancer
  # this shows how to customize the Kibana pod
  # with labels and resource limits
  podTemplate:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 1Gi
            cpu: 1